version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: user_management
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 